[global]
# size in MB
segment_size_mb 128

[devices]
# size in MB
dev path=/dev/dax0.0 size_mb=20480
dev path=/dev/dax0.1 size_mb=20480
dev path=/dev/dax1.0 size_mb=20480

[clouddb]
enable_clouddb false
influxdb_url <url>
influxdb_token <token>
